import pygame
WIDTH = 1280
HEIGHT = 720

PADDLE_SPEED = 600
EASY_AI_SPEED = 400
PADDLE_SIZE = 60
#Game state
MENU = 'menu'
PREPARE = 'prepare'
START = 'start'
SERVE = 'serve'
UPGRADE = 'upgrade'
SPEED = 'speed'
SIZE = 'size'
RESET = 'reset'
EXIT = 'exit'
BACK = 'back'
#GAME_MODE
PLAYER_VS_BOT = 'bot'
PLAYER_VS_PLAYER = 'player'

#Key Press
W = pygame.K_w
S = pygame.K_s
KEYUP = pygame.K_UP
KEYDOWN = pygame.K_DOWN
ENTER = pygame.K_RETURN

WINNING_SCORE = 2
MAX_FRAME_RATE = 144
#COLOR CODE
WHITE = (255, 255, 255)
YELLOW = (247, 247, 73)
#PAGE
MENU_PAGE = {
    START: {START: YELLOW, UPGRADE: WHITE, EXIT: WHITE},
    UPGRADE: {START: WHITE, UPGRADE: YELLOW, EXIT: WHITE},
    EXIT: {START: WHITE, UPGRADE: WHITE, EXIT: YELLOW}
}

UPGRADE_PAGE = {
    SPEED: {SPEED: YELLOW, SIZE: WHITE, RESET: WHITE, BACK: WHITE},
    SIZE: {SPEED: WHITE, SIZE: YELLOW, RESET: WHITE, BACK: WHITE},
    RESET: {SPEED: WHITE, SIZE: WHITE, RESET: YELLOW, BACK: WHITE},
    BACK: {SPEED: WHITE, SIZE: WHITE, RESET: WHITE, BACK: YELLOW},
}

PREPARE_PAGE = {
    PLAYER_VS_BOT: {PLAYER_VS_BOT: YELLOW, PLAYER_VS_PLAYER: WHITE, BACK: WHITE},
    PLAYER_VS_PLAYER: {PLAYER_VS_BOT: WHITE, PLAYER_VS_PLAYER: YELLOW, BACK: WHITE},
    BACK: {PLAYER_VS_BOT: WHITE, PLAYER_VS_PLAYER: WHITE, BACK: YELLOW}
}
#component pos
POSITIONS_3 = {
    1: (WIDTH / 2, HEIGHT / 2 - 60),
    2: (WIDTH / 2, HEIGHT / 2),
    3: (WIDTH / 2, HEIGHT / 2 + 60)
}

POSITIONS_4 = {
    1: (WIDTH / 2, HEIGHT / 2 - 90),
    2: (WIDTH / 2, HEIGHT / 2 - 30),
    3: (WIDTH / 2, HEIGHT / 2 + 30),
    4: (WIDTH / 2, HEIGHT / 2 + 90)
}